# Generated by Django 2.0.1 on 2018-01-31 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180131_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storageinstance',
            old_name='yeastStatus',
            new_name='storStatus',
        ),
    ]
