# Generated by Django 2.0.1 on 2018-05-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180131_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yeast',
            name='dateIsolated',
        ),
        migrations.RemoveField(
            model_name='yeast',
            name='source',
        ),
        migrations.RemoveField(
            model_name='yeast',
            name='yeastType',
        ),
        migrations.AddField(
            model_name='yeast',
            name='lower_temp',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='yeast',
            name='upper_temp',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='yeast',
            name='yeast_type',
            field=models.CharField(blank=True, choices=[('Ale', 'Ale'), ('Cider', 'Cider'), ('Champagne', 'Champagne'), ('Wine', 'Wine')], help_text='Yeast type', max_length=10),
        ),
        migrations.AlterField(
            model_name='storageinstance',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.DeleteModel(
            name='YeastType',
        ),
    ]
