# Generated by Django 2.0.1 on 2018-05-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_yeast_cetegory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='storageinstance',
            options={'ordering': ['yeast', 'date_created']},
        ),
        migrations.RenameField(
            model_name='media',
            old_name='dateCreated',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='medType',
            new_name='media_type',
        ),
        migrations.RenameField(
            model_name='storageinstance',
            old_name='dateCreated',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='storageinstance',
            old_name='dateInoc',
            new_name='date_inoculated',
        ),
        migrations.RenameField(
            model_name='storageinstance',
            old_name='storStatus',
            new_name='storage_status',
        ),
        migrations.RemoveField(
            model_name='storageinstance',
            name='storageType',
        ),
        migrations.AddField(
            model_name='storageinstance',
            name='storage_type',
            field=models.CharField(blank=True, choices=[('s', 'Slant'), ('p', 'Plate'), ('sol', 'Solution'), ('f', 'Freeze'), ('o', 'Other')], help_text='Select the appropriate yeast storage category', max_length=100),
        ),
        migrations.DeleteModel(
            name='StorageType',
        ),
    ]
