# Generated by Django 2.0.1 on 2018-05-11 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180511_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageinstance',
            name='yeast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Yeast'),
        ),
    ]
