# Generated by Django 2.0.1 on 2018-05-11 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20180511_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['date_created'], 'verbose_name_plural': 'Media'},
        ),
    ]
