# Generated by Django 2.0.1 on 2018-05-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20180511_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yeast',
            old_name='cetegory',
            new_name='category',
        ),
    ]
