# Generated by Django 2.0.1 on 2018-05-11 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20180511_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yeast',
            old_name='category',
            new_name='character',
        ),
    ]
