# Generated by Django 2.0.1 on 2018-05-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20180511_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yeast',
            name='yeast_type',
            field=models.CharField(blank=True, choices=[('Ale', 'Ale'), ('Lager', 'Lager'), ('Cider', 'Cider'), ('Champagne', 'Champagne'), ('Wine', 'Wine')], help_text='Yeast type', max_length=10),
        ),
    ]
