# Generated by Django 2.0.1 on 2018-05-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20180511_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageinstance',
            name='storage_status',
            field=models.CharField(choices=[('u', 'Used'), ('i', 'Inoculated'), ('a', 'Available')], help_text='Select the appropriate media type', max_length=100),
        ),
    ]
