# Generated by Django 2.0.1 on 2018-06-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20180511_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageinstance',
            name='storage_status',
            field=models.CharField(choices=[('u', 'Used / Discarded'), ('i', 'Inoculated'), ('a', 'Available')], help_text='Select the appropriate media type', max_length=100),
        ),
    ]
