# Generated by Django 2.0.1 on 2018-07-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20180606_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storageinstance',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='storageinstance',
            name='storage_type',
            field=models.CharField(choices=[('s', 'Slant'), ('p', 'Plate'), ('sol', 'Solution'), ('f', 'Freeze'), ('o', 'Other')], help_text='Select the appropriate yeast storage category', max_length=100),
        ),
    ]
