# Generated by Django 2.0.1 on 2018-07-16 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20180707_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageinstance',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.StorageInstance'),
        ),
        migrations.AlterField(
            model_name='storageinstance',
            name='date_created',
            field=models.DateField(null=True),
        ),
    ]
